- ReportingServicesTools.psd1
Added "SSRS" tag so that more people might be able to find this module
in the PowerShell Gallery.
> Added Tags for the PowerShell Gallery

- Functions/CatalogItems/Write-RsCatalogItem.ps1
- Functions/Common/Get-ItemType.ps1
Pulled the logic for the Get-ItemType "utility" function out of
Write-RsCatalogItem, converted it to a switch statement, and placed it
in the Common folder.
> Get-ItemType

- Functions/CatalogItems/Out-RsCatalogItem.ps1
- Functions/Common/Get-FileExtension.ps1
Removed inline function and moved it to "Common".  Added pipeline
bingding, process, & foreach to support pipelining of multiple SSRS
objects to be exported.
> Similar Changes as were done to Write-RsFolderContent 

- Functions/CatalogItems/Get-RsFolderContent.ps1
- Functions/CatalogItems/New-RsDataSource.ps1
- Functions/CatalogItems/Out-RsCatalogItem.ps1
- Functions/CatalogItems/Out-RsFolderContent.ps1
- Functions/CatalogItems/Remove-RsCatalogItem.ps1
- Functions/CatalogItems/Write-RsCatalogItem.ps1
- Functions/CatalogItems/Write-RsFolderContent.ps1
Replaced -Destination DestinationFolder parameters in favor of -RsFolder
for increased clarity; added aliases to reference these previous
commands.  Modified Help examples with these changes as well.
> Replaced -Destination -DestinationFolder params in favor of -RsFolder

- Tests/CatalogItems/Get-RsFolderContent.Tests.ps1
> Creation of Get-FolderContent test

- Tests/CatalogItems/Get-RsDataSource.Tests.ps1
- Tests/CatalogItems/New-RsDataSource.Tests.ps1
> Add Get-RsDataSource Test

- README.md
- src/Functions/Common/ConnectionObjectRequests.ps1
- src/Functions/Utilities/New-RsConfigurationSettingObject.ps1
- src/Libraries/library.ps1
- Adding support for SQL Server 2017
- Try to use this project against SQL Server 2017 or Power BI Report Server
- Powershell 3
- Windows 10
- Power BI Report Server
> Adding support for sql2017

- README.md
- ReportingServicesTools/Functions/Admin/Initialize-Rs.ps1
- ReportingServicesTools/Functions/Admin/Set-RsUrlReservation.ps1
- Updated Read Me to include information on Initialize-Rs and Set-RsUrlReservation
- Added some more logging to Initialize-Rs and Set-RsUrlReservation
> Minor changes to Readme

- README.md
Markdown formatting changes only
> chore: fix README markdown headings

- README.md
Documentation/Syntax highlighting only
> chore: syntax highlight code blocks in README

- ReportingServicesTools/Functions/CatalogItems/Get-RsSubscription.ps1
- ReportingServicesTools/Functions/CatalogItems/Remove-RsSubscription.ps1
- ReportingServicesTools/Functions/CatalogItems/Set-RsSubscription.ps1
- ReportingServicesTools/ReportingServicesTools.psd1
- Tests/Admin/RsEncryptionKey.Tests.ps1
- Tests/CatalogItems/Get-RsSubscription.Tests.ps1
- Tests/CatalogItems/Remove-RsSubscription.Tests.ps1
- Tests/CatalogItems/Set-RsSubscription.Tests.ps1
- appveyor.yml
Get-RsSubscription
Set-RsSubscription
Remove-RsSubscription
Also the Pester tests for each one
> New Commands to Handle Subscriptions

- ReportingServicesTools/Functions/CatalogItems/Remove-RsSubscription.ps1
- ReportingServicesTools/Functions/CatalogItems/Set-RsSubscription.ps1
Quick improvement.
Also fix some curly bracket position.
> Added Support for subscription Values (parameters) 

- README.md
- ReportingServicesTools/Functions/Admin/Set-PbiRsUrlReservation.ps1
- ReportingServicesTools/Functions/Admin/Set-RsUrlReservation.ps1
- ReportingServicesTools/ReportingServicesTools.psd1
- appveyor.yml
> Reserve powerbi and office webapp urls

- ReportingServicesTools/Functions/CatalogItems/Write-RsFolderContent.ps1
Fixes #73.
- Bug fix for uploading shared data source via Write-RsFolderContent.
> Adding support for shared data sources

- README.md
Just proposing a small improvement to the README for people who are less familiar with PowerShell (which is 80% of all people who use PowerShell just to get stuff done they used to do manually).
> Explain to user how to check PS version.

- ReportingServicesTools/Functions/Security/Grant-RsCatalogItemRole.ps1
- Tests/Security/AccessOnCatalogItem.Tests.ps1
> Fixes (#102) - Can't add more than one Role for same user using Grant-RsCatalogItemRole

- Install.ps1
Fixes #108.
- Updated the location of ReportingServicesTools.psd1
- Run .\Install.ps1
- Powershell 5
- Windows 10
> Fixing Install.ps1

- README.md
- Updates to Readme contents adding commands & Alias info
- N/A
N/A
> Added missing commands & alias info to Readme

- README.md
> Shouldn't this be get instead of set?

- ReportingServicesTools/Functions/CatalogItems/Write-RsCatalogItem.ps1
> Fix #181 Typo in Write-RsCatalogItem

- ReportingServicesTools/Functions/Common/ConnectionObjectRequests.ps1
> #183 doc omission of RestApiVersion key in New-RsRestSessionHelper

- ReportingServicesTools/Functions/Admin/Set-RsDatabaseCredentials.ps1
- ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestFolder.ps1
- ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataSource.ps1
- ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
- ReportingServicesTools/Functions/CatalogItems/Write-RsFolderContent.ps1
- ReportingServicesTools/Functions/Security/Grant-RsCatalogItemRole.ps1
- #162 
- #178
- #189
- #196 
- #202
Please see the issues
- SQL Server 2016 and SSRS PBIRS 2017
> Various fixes

- ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
- A minor commit which changes the "Wrote-Error" statement to "Write-Error"
> Fix the print statement "Wrote-Error"

- ReportingServicesTools/Functions/CatalogItems/New-RsSubscription.ps1
Description for parameter FileWriteMode was incorrect. This simply fixes the description
N/A just look at the description
> Corrected parameter description

- ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestFolder.ps1
Fixes # .
This fixes the bug introduced in pull #234 
Incorrectly sets parameter UseBasicParsing twice.
> remove bugfrom other PR

- README.md
Updating readme page to add Power BI Report Server and SSRS 2019
Fixes # .
- 
- 
- 
- 
- 
- 
> Updating readme page to add Power BI Report Server and SSRS 2019

- README.md
> Missing word in readme

- ReportingServicesTools/Functions/CatalogItems/New-RsSubscription.ps1
Fixes #97 .
Tested on SQL Server 2016, PowerShell 5, Windows Server 2016
> Added support for passing in Report Parameters

- Tests/CatalogItems/Rest/Get-RsRestFolderContent.Tests.ps1
- Tests/CatalogItems/Rest/Get-RsRestItem.Tests.ps1
Fixes 2
- Moved location of test variable output to display properly.
- Run the build process.
- PowerShell 5.1
- Windows 10
- Power BI Report Server
> Fixing tests

- README.md
Fixes # 4
- Updated and clarified README.md file
- `Get-Command -Module ReportingServicesTools`
- PowerShell 5.1 and above
- Power BI Report Server 2020 and above
> Updated and clarified README.md file.

- ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestCacheRefreshPlanHistory.ps1
- ReportingServicesTools/ReportingServicesTools.psd1
- Tests/CatalogItems/Rest/Get-RsRestCacheRefreshPlanHistory.Tests.ps1
- Added new Get-RsRestCacheRefreshPlanHistory function and pester test.
- Use the pester test included in this PR
- PowerShell 7.1 and above
- Windows 10
- PBIRS
> Added Get-RsRestCacheRefreshPlanHistory function and test.

- ReportingServicesTools/Functions/Security/Rest/Grant-RsRestItemAccessPolicy.ps1
- ReportingServicesTools/Functions/Security/Rest/Revoke-RsRestItemAccessPolicy.ps1
- ReportingServicesTools/ReportingServicesTools.psd1
- Tests/Security/Rest/AccessPolicyOnRsRestItem.Tests.ps1
- Added Grant-RsRestItemAccessPolicy function
- Added AccessPolicyOnRsRestItem.Tests.ps1 pester test
- Use the included pester test.
- PowerShell 7.1
- Windows 10
- PBIRS
> SQLvariant add Grant-RsRestItemAccessPolicy

- README.md
- ReportingServicesTools/Functions/Security/Rest/Grant-RsRestItemAccessPolicy.ps1
- ReportingServicesTools/Functions/Security/Rest/Revoke-RsRestItemAccessPolicy.ps1
- Added descriptions for the Grant & Revoke -RsRestItemAccessPolicy functions to the List of Commands.
- N/A
- N/A
> SQLvariant readme-md

- README.md
See discussion in ISSUE-345
Fixes #345 .
- README.md change, per discussion in ISSUE-345.
- n/a - documentation change only
> Add note for preferred install method

- ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
Fixes absence of `Hidden` parameter for Write-RsRestCatalogItem
- add `Hidden` parameter to Write-RsRestCatalogItem
- update documentation
- clean up Overwrite upload section
- `Write-RsRestCatalogItem -WebSession $session -Path 'your_path_here' -RsFolder 'target_path_here' -Hidden`
- See your selected item on report server marked as `Hidden`
---
Details
The following can now be uploaded as hidden:
- DataSource
- Kpi
- all others except large power bi report files (>=MinLargeFileSizeInMb)
Clarify documentation of
- `Description`
- `Overwrite`
to be ignored by large Power BI Report files.
Add documentation …
> [Write-RsRestCatalogItem] add `Hidden` parameter

- README.md
- ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestDataSource.ps1
- ReportingServicesTools/Functions/Common/New-RestSessionHelperSplat.ps1
- ReportingServicesTools/ReportingServicesTools.psd1
- Tests/CatalogItems/Rest/Get-RsRestDataSource.Tests.ps1
Fixes #399 .
- new helper func New-RestSessionHelperSplat
- new func Get-RsRestDataSource
- 
- Peter test included
Has been tested on:
- Powershell 5.1 and 7.2.11
- Windows 10
> New-function-Get-RsRestDataSource

- ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1
- ReportingServicesTools/Functions/Admin/Set-RsDatabaseCredentials.ps1
Reverts microsoft/ReportingServicesTools#401
> Revert "Updated Set-RsDatabase and Set-RsDatabaseCredentials scripts to support new parameters of Invoke-Sqlcmd."
