Functions/CatalogItems/Out-RsFolderContent.ps1
Functions/CatalogItems/Write-RsFolderContent.ps1

Fixing scripts for the special case where the target folder is the root folder. Concatenating target folder to the relative path to the new item has to be handled differently in these cases.

Fixing Out-RsFolderContent and Write-RsFolderContent 

---

Functions/CatalogItems/Get-RsFolderContent.ps1

Cleaned up the original example by removing unnecessary tick marks.
Updated Help on Get-RsFolderContent with more examples; one to point out
the -Recurse parameter, the other is a duplicate of the example from the
Out-RsCatalogItem function to show that you can use the two commands
together via the pipeline.

Updated Help on Get-RsFolderContent with more examples

---

ReportingServicesTools/Functions/CatalogItems/New-RsDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Set-RsDataSource.ps1
Tests/CatalogItems/New-RsDataSource.Tests.ps1
Tests/CatalogItems/Set-RsDataSource.Tests.ps1

Fixes #39 
- Added option to specify a description when creating or modifying a Shared Data Source.
- Tests were added.
- Powershell 4 
- Windows 10 
- Power BI Report Server

Adding support for shared data source description

---

ReportingServicesTools/Functions/CatalogItems/Set-RsSubscription.ps1

A user reported that receives an error when try to copy the subscription for a report type 'LinkedReport'.
> You get the error ItemType ‘LinkedReport’ is not supported by this.
This PR, includes a better way to validate if the destination report exists.
Before was using the Get-RsItemReference to validate the existence of it but this is not the correct way.

Set-RsSubscription - Change the logic of validation if destination report exists

---

ReportingServicesTools/Functions/Admin/Set-RsUrlReservation.ps1

- Altered the PowerShell script to accept a custom listening port for the Web UI.
- Just test it manually. Need some help with that to write some automation tests.

Parametrize the Web UI listening port

---

ReportingServicesTools/Functions/Utilities/New-RsRestSession.ps1
Tests/Utilities/NewRsRestSessionTests.ps1

- When creating a new Rest Session, we will now validate if the user had provided a valid URL to Report Portal
- Added tests to test this code.

Validating url specified to New-RsRestSession is url to Report Portal

---

README.md

The word "downloads" was missing from the description of the `Out-RSFolderContent` cmdlet.
Fixes # .
- 
- 
- 
- 
- 
- 

Missing word in readme.md

---

ReportingServicesTools/Functions/CatalogItems/Write-RsCatalogItem.ps1

Fixes issue #91
- Use Write-Warning to forward to user warnings reported by the report server
- These warnings are not captured in Visual Studio when compiling, and, to the best of my knowledge, can only be data mined during deployment, making it incredibly valuable to surface to the user doing deployments
- I'm open to suggestions
- Powershell 5 and above

 Forward CreateCatalogItem $warnings to Warning output stream

---

ReportingServicesTools/Functions/Utilities/New-RsWebServiceProxy.ps1

Fixes #88.
- Verbose logs the Report Server Uri when the Web Service Proxy is being created
- No test added as there was no functional change to any of the scripts.

Fix for verbose logging ReportServerUri when creating proxy

---

ReportingServicesTools/Functions/CatalogItems/New-RsSubscription.ps1

Fixes #85.
- Add ExcludeLink and Priority as valid Email parameters
- Enforce valid set of Priorty options
- Enforce default value of NORMAL for Priority
- I'm open to suggestions
- Powershell 5 and above

Add ExcludeLink and Priority as Email options

---

ReportingServicesTools/Functions/CatalogItems/Remove-RsCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItemId.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/Common/Get-FileExtension.ps1
ReportingServicesTools/Functions/Common/Get-ItemType.ps1
Tests/CatalogItems/Rest/New-RsRestFolder.Tests.ps1
Tests/CatalogItems/Rest/Out-RsRestCatalogItem.Tests.ps1
Tests/CatalogItems/Rest/Out-RsRestFolderContent.Tests.ps1
Tests/CatalogItems/Rest/Remove-RsRestCatalogItem.Tests.ps1
Tests/CatalogItems/Rest/Remove-RsRestFolder.Tests.ps1
Tests/CatalogItems/Rest/Write-RsRestCatalogItem.Tests.ps1
Tests/CatalogItems/Rest/Write-RsRestFolderContent.Tests.ps1
Tests/CatalogItems/testResources/NewKPI.kpi
Tests/CatalogItems/testResources/emptyFile.txt

- Added support for downloading KPIs
- Added support for uploading KPIs
- Made a minor change to one of the parameters in Remove-RsCatalogItem
- Tests were added
- Powershell 5
- Windows 10
- SQL Server 2017, Power BI Report Server

Adding support for migrating KPI across servers

---

ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestFolderContent.ps1
Tests/CatalogItems/Rest/Write-RsRestFolderContent.Tests.ps1

Fixes #113 .
- Adds `$Overwrite` parameter to `Write-RsRestFolderContent`
- Passes `$Overwrite` and `$Credential` from `Write-RsRestFolderContent` to `Write-RsRestCatalogItem`
- Have not tested, sorry
- Powershell 5.1.16299.15
- Windows 10
- Power BI Reporting Server

`Write-RsRestFolderContent` does not pass $Credential and $Overwrite

---

README.md
ReportingServicesTools/Functions/CatalogItems/Update-RsSubscription.ps1
ReportingServicesTools/ReportingServicesTools.psd1
Tests/CatalogItems/Update-RsSubscription.Tests.ps1

Altered readme
Altered PSD1
Added Pester Tests
Added Update-RsSubscription function
Fixes # 66 (add update functions)
- Add cmdlet Update-RsSubscription to edit subscripton startdatetime, endate or owner piped from existing Get-RsSubscription cmdlet
- Pester test included Update-RsSubscription.tests.ps1
- Manual Update existing subscription on local SSRS: 
Get-RsSubscription -path '/Finance/ImportantReports' | Update-RsSubscription -EndDate 9/9/2099
- 

Added Update-RsSubscription

---

ReportingServicesTools/Functions/Security/Get-RsCatalogItemRole.ps1
ReportingServicesTools/Functions/Utilities/New-RsCatalogItemRoleObject.ps1

Fixes # . I missed a commit where I added the Mandatory Parameter for New-RsCatalogItemRoleObject when creating the root item.
- I have added a property to the Get-RsCatalogItemRole function that shows if inheritance/Parent Security is enabled for each item.
- 
- 
- 
- 
- 

Added a Parent Security property to Get-RsCatalogItemRole

---

ReportingServicesTools/Libraries/library.ps1

- Extending the ReportServerVersion enum to include SQL Server vNext
- Powershell 5
- Windows 10
- Power BI Report Server

Adding support for SQL Server vNext

---

ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestFolderContent.ps1

Recurse parameter should be inherited in order to get real recursive behaviour. Otherwise it only works for one subfolder layer.

Inherit recurse parameter

---

ReportingServicesTools/Functions/CatalogItems/Copy-RsSubscription.ps1

Fixes #136 and #137.
- Variable used to check for DataDriven subscription was the collection and not the current item.
- The input validation was moved to the Begin block
Please take a look at issues #136 and #137
- Powershell 5
- Windows 10
- SQL Server 2016/2017

Subscription fix

---

ReportingServicesTools/Functions/Security/Grant-RsCatalogItemRole.ps1

Fixes #139.
- More verbose message when it fails
- Grant "NETWORK SERVICE" permissions using 
`Grant-RsCatalogItemRole -Proxy $proxy -Path "/London" -RoleName 'Publisher' -Identity 'NETWORK SERVICE'`
And then add again another different role
`Grant-RsCatalogItemRole -Proxy $proxy -Path "/London" -RoleName 'Browser' -Identity 'NETWORK SERVICE'`
- Powershell 5
- Windows 10

Improve Error message on Grant-RsCatalogItemRole

---

ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1

Fixes #144 
- Add option to choose authentication credentials for setup steps in `Set-RsDatabase`
- Add options to enable/disable discrete setup steps in `Set-RsDatabase`
- Run it
- SQL Server 2016 so far. 
A number of points:
* Have not fully tested. I see the tests folder and the `Set-RsDatabase.Tests.ps1`; what harnesses need to be in place to run them?
* Don't have easy access to all of the above environments, so would like some help in testing
* I am not sure this is the best approach. I wonder if breaking them out into separate commands - `Setup-RsDatabase` which does the admin work and `Set-RsDatabase` which _only_ configures the PBIRS isn't a better approach. 
As …

Control admin vs runtime setup

---

ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1

Fixes # .
- Error caused by extraneous `[Parameter]`; see [comment](https://github.com/Microsoft/ReportingServicesTools/pull/146#issuecomment-367858303) by @jtarquino 
- install and run

Removed extraneous Parameter which was breaking

---

ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Write-RsFolderContent.ps1
Tests/CatalogItems/Rest/Write-RsRestFolderContent.Tests.ps1
Tests/CatalogItems/Write-RsFolderContent.Tests.ps1

Fixes:
- #114 
- #124 
- #157 
- #158 
- Handle when folder do not exist (Both commands)
- Better error message and handle next item on error. (Rest command)
- Please take a look on the issue that this PR solves.
- Powershell 5
- Windows 10 

Fixes&enhancements to Write-Rs(Rest)FolderContent commands

---

ReportingServicesTools/Functions/Security/Get-RsCatalogItemRole.ps1

Fixes #153 .
- The first assignment needs to be a `+=` instead of just `=` otherwise we lose the collection and inside `-Recurse` the `+=` will fail.
- Please take a look on issue #153
- Windows 10

Get-RsCatalogItemRole with -Recurse 

---

Install.ps1

- Allow the install script to be able to pick anther tag or branch than `master`, but fall back to the existing behaviour.
- Ensure the webrequest to GH is using TLS 1.2 since older crypto has been turned off a few months ago https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/
- `.\Install.ps1 -Version 0.0.4.6`

Add parameter to Install.ps1 to specify version

---

ReportingServicesTools/Functions/Utilities/Connect-RsReportServer.ps1

"Version" parameter in the comment-based help was mismatched with "ReportServerVersion" in the actual function definition. I believe this was causing blank documentation to be generated for get-help.
- Corrects mismatched parameter name in comment-based help.
- Build help files for this function and verify that the help text appears for `Get-Help Connect-RsReportServer -Parameter ReportServerVersion`

Fixed mismatched parameter name in help text

---

ReportingServicesTools/Functions/CatalogItems/New-RsFolder.ps1
Tests/CatalogItems/New-RsFolder.Tests.ps1

Fixes #145 .
- Addition of `-Description` parameter
- Includes Examples of parameter use
- Refactored `New-RsFolder.Tests.ps1` to include a check for a new Description
- Execute `New-RsFolder -RsFolder '/' -FolderName 'MyDescriptiveReports' -Description 'This folder contains Descriptive Reports'`
- Execute `New-RsFolder.Tests.ps1`
- Windows 10 

Add 'Description' parameter; Include check in existing Pester test

---

ReportingServicesTools/Functions/CatalogItems/New-RsFolder.ps1
ReportingServicesTools/Functions/CatalogItems/Write-RsCatalogItem.ps1
Tests/CatalogItems/New-RsFolder.Tests.ps1
Tests/CatalogItems/Write-RsCatalogItem.Tests.ps1

Fixes #76.
- Add Hidden parameter to the New-RsFolder and Write-RsCatalogitem methods to allow creation of hidden folders and catalog items
- Add Name parameter to the Write-RsCatalogitem method to allow the name to be different to the name of the file being uploaded
- Added unit tests to New-RsFolder.Tests.ps1 and Write-RsCatalogItem.Tests.ps1
- Powershell 5
- Windows 10

fix #76 Allow setting Hidden attribute on Folders and Hidden and Name on Catalog Items

---

ReportingServicesTools/Functions/Security/Get-RsCatalogItemRole.ps1

Small bugfix to fix the fact that Get-RsCatalogItemRole always returns false when not used with -Recurse on the ParentSecurity property, even if permissions are inherited.

Get-RsCatalogItemRole: fix bug that would always return false on inherited security

---

ReportingServicesTools/Functions/Admin/Restore-RsEncryptionKey.ps1

Fixes #228  .
- Added code to handle restarting RS service with alternate credential by using Get-WmiObject
Assuming that `adminuser` user has access to the computer SSRS and the user running the command does not:
```powershell
Restore-RSEncryptionKey -KeyPath 'C:\MyFolder\MyKeyFile.snk' -Password 'MyPass' -ComputerName SSRS -Credential (Get-Credential adminuser)
```
- Windows 10
- SQL Server 2016

Added code to handle restarting RS service with alternate credential

---

ReportingServicesTools/Functions/Common/ConnectionObjectRequests.ps1
ReportingServicesTools/Functions/Utilities/Connect-RsReportServer.ps1
ReportingServicesTools/Functions/Utilities/New-RsWebServiceProxy.ps1

Enabling `CustomAuthentication` switch to invoke `LogonUser` method upon establishing a connection via the SOAP API with the passed credentials.
Fixes #160.
- Adds `CustomAuthentication` switch to `Connect-RsReportServer` and all other cmdlets that take `Credentials` and `ReportPortalUri` individually.
- Prompts for `Credentials` (via `Get-Credentials`) if none is passed via the equivalent parameter.
- Executes the `LogonUser` SOAP API method upon creating the Web Service Proxy with the passed credential and stores the cookie in the session for subsequent calls.
- `Connect-RsReportServer -ReportServerUri http://localhost/ReportServer -CustomAuthentication -Verbose`
- `Get-RsCatalogItems -RsFolder /`
Has been tested on (remove …

CustomAuthentication switch

---

ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1

- #269
- Added QueryTimeout parameter for Set-RsDatabase function. This will give us the opportunity to control the timeout of the query.
- Please see the issue
- Powershell 3
- Windows 10
- PBIRS September 2019

Added QueryTimeout parameter for Set-RsDatabase function

---

ReportingServicesTools/Functions/CatalogItems/Out-RsFolderContent.ps1
ReportingServicesTools/Functions/Common/Get-FileExtension.ps1

Fixes #279.
- Add file extension matching report part
- Add type name matching report part
- 
- Connect Connect to SSRS using `Connect-RsReportServer`
- Execute` Out-RsFolderContent` pointing to folder containing report parts
- Check if report parts is downloaded

Added support for report parts

---

ReportingServicesTools/Functions/CatalogItems/Get-RsDeploymentConfig.ps1
ReportingServicesTools/Functions/CatalogItems/Publish-RsProject.ps1
Tests/CatalogItems/Publish-RsProject.Test.ps1

Added logic to prepend folders with '/' when needed.
Only affects $TargetReportFolder, $TargetDatasourceFolder, $TargetDatasetFolder
Fixes issue when .rptproj file contains $TargetReportFolder, $TargetDatasourceFolder, and/or $TargetDatasetFolder which do not begin with '/'.
- Added logic to prepend folders with '/' when needed
- Updated Test to include this scenario - 
- Use the updated Publish-RsProject.Test.ps1 file.
- PowerShell 5.1 and above
- Power BI Report Server and above

Added logic to prepend folders with / when needed

---

ReportingServicesTools/Functions/CatalogItems/Out-RsCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Out-RsFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItemId.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestFolderContent.ps1

Fixes #302
- Added -LiteralPath to Test-Path in parameter on Out-RsRestCatalogItem, Out-RsRestCatalogItemId, Out-RsRestFolderContent, Out-RsCatalogItem and Out-RsFolderContent
- Added -LiteralPath to Convert-Path on RsRestCatalogItemId, Out-RsCatalogItem and Out-RsFolderContent
- Run it on regular folders without issue, as before
- Run it on folders that have [] in their name
- Powershell 5 and Powershell 7
- Windows 10 and Windows Server 2019
- PowerBI Report Server September 2019

Add -LiteralPath to Test-Path and Convert-Path

---

README.md
ReportingServicesTools/Functions/CatalogItems/Rest/Test-RsRestItemDataSource.ps1
ReportingServicesTools/ReportingServicesTools.psd1
Tests/CatalogItems/Rest/Test-RsRestItemDataSource.Tests.ps1

- Added Test-RsRestItemDataSource function found in Test-RsRestItemDataSource.ps1
- Test-RsRestItemDataSource.Tests.ps1
- Use the pester test found in Test-RsRestItemDataSource.Tests.ps1
- PowerShell 7.1 and above
- Windows 10
- PBIRS

SQLvariant Test-RsRestItemDataSource

---

ReportingServicesTools/Functions/CatalogItems/Get-RsDeploymentConfig.ps1
Tests/CatalogItems/Get-RsDeploymentConfig.Tests.ps1
Tests/CatalogItems/TestProjects/SQLServerPerformanceDashboardReportingSolution/SQL Server Performance Dashboard/SQL Server Performance Dashboard.rptproj

Adding NULL handling for Dataset, Datasource, & ReportPart folders.
Fixes #319  .
- Added handling of NULL for Dataset, Datasource, & ReportPart folders proposed in #319
- Use the Pester test.
- PowerShell 5.1
- Windows 10
- PBIRS

Adding NULL handling for target folders

---

ReportingServicesTools/Functions/Admin/Restore-RsEncryptionKey.ps1

Fixes #159 .
- Change service name if SSRS (default for newer versions) is the  Instance Name
- Restore-RsEncryptionKey -ComputerName Name -ReportServerVersion 15 -ReportServerInstance SSRS -Password 'Pass' -KeyPath 'C:\Folder\File.snk'
- Powershell 5 and above
- SQL Server 2019 and above

Update SSRS Service name for newer versions

---

ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/ReportingServicesTools.psd1
Tests/CatalogItems/Rest/Remove-RsRestCacheRefreshPlan.Tests.ps1

Added function to remove scheduled refresh (CacheRefeshPlan) from a PBIX file to complement the existing Get, Create, Start functions for scheduled refresh.
- Add function to delete scheduled refresh (CacheRefreshPlan)
- Run Remove-RsCacheRefreshPlan -RsReport '/MyReport' . Note that this works if there is only ONE scheduled refresh
- Run Remove-RsCacheRefreshPlan -ID $scheduleID to delete a specific scheduled refresh using the schedule ID
-To get an id, run $scheduleID = (Get-RsCacheRefreshPlan -RsReport '/MyReport').ID[0] 
Has been tested on :
- PowerShell 5
- Windows 10
- Windows Server 2016

Add function to remove Scheduled Refresh from a PBIX report

---

ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItemDataModelParameters.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataModelParameters.ps1
ReportingServicesTools/ReportingServicesTools.psd1
Tests/CatalogItems/Rest/Get-RsRestItemDataModelParameters.Tests.ps1
Tests/CatalogItems/Rest/Set-RsRestItemDataModelParameters.Tests.ps1

Removed the plural s from DataModelParameters from the Get-RsRestItemDataModelParameters & Set-RsRestItemDataModelParameters functions, to meet the PowerShell naming standard.
- Removed the plural s from the Get-RsRestItemDataModelParameters function, added an alias.
- Removed the plural s from the Set-RsRestItemDataModelParameters function, added an alias.
- Updated the corresponding tests as well.
- Run the updated Pester tests.
- PowerShell 7.1
- Windows 10
- PBIRS

Removed the plural s from DataModelParameters

---

ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestCacheRefreshPlan.ps1

Fixes #337  .
- Add Description parameter and update param binding
`New-RsRestCacheRefreshPlan -RsItem $rsItemName -ReportPortalUri $reportPortalUri -Description "temp" -WebSession $session -RestApiVersion $ApiVersion`
Has not been tested.

Fixed missing param on New-RsRestCacheRefreshPlan

---

ReportingServicesTools/ReportingServicesTools.psd1

Fixes #[343](https://github.com/microsoft/ReportingServicesTools/issues/343) .
- Update ModuleVersion in ReportingServicesTools.psd1
1. Uninstall the current version of ReportingServicesTools
2. Install via one of the two Invoke-Expression installation methods
`Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/ReportingServicesTools/master/Install.ps1)`
or
`Invoke-Expression (Invoke-WebRequest https://aka.ms/rstools)`
3. Note as part of the installation, the installed commands are returned and show version 0.0.6.6
- Powershell versions 5.1.19041.1023 and 7.1.4
- Windows 10

Update ModuleVersion in manifest

---

ReportingServicesTools/Functions/CatalogItems/New-RsDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Write-RsCatalogItem.ps1
Tests/CatalogItems/New-RsDataSource.Tests.ps1
Tests/CatalogItems/Write-RsCatalogItem.Tests.ps1

`New-RsDataSource` is lacking a `$Hidden` switch parameter to create hidden data sources.
`Write-RsCatalogItem` has a `$Hidden` switch parameter, but it is not passed to `New-RsDataSource`.
The tests for `Write-RsCatalogItem` didn't verify that items created were in fact hidden.
Specifically, "Should upload a local RsDataSource in Report Server" in context "Write-RsCatalogItem with hidden parameters" passed `$Hidden` to `Write-RsCatalogItem`, which created the data source, but the data source was not hidden.
- Added `$Hidden` parameter to `New-RsDataSource`, with doc comment
- Changed `Write-RsCatalogItem` to pass `$Hidden` switch to `New-RsDataSource` 
- Added test for `New-RsDataSource` with `$Hidden` switch parameter
- Added assertions to all …

Support for creating hidden datasources using New-RsDataSource, and assertions for Write-RsCatalogItem that items are created as hidden when specified

---

ReportingServicesTools/Functions/CatalogItems/Set-RsSubscription.ps1

Fixes #356 
- Execute $proxy.SetSubscriptionProperties if $subproperties not null
- Added context help for $subproperties parameter
- Get-RsSubscription | Set-RsSubscription 
- 
- 
- ReportingService2010 soap endpoint

Feature/bug fix for Set-RsSubscription to check for $subproperties -ne $null

---

ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItemDataModelParameters.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItemDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestFolder.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItemId.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataModelParameters.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestFolderContent.ps1

Should fix #314
Fixes #314.
- Add `-UseBasicParsing` to all `Invoke-WebRequest` calls
- Use any of the `Rest` tools on a system running Powershell 5.1
Has NOT been tested:
- Need to test

fix: Add -UseBasicParsing to all Invoke-WebRequest calls

---

ReportingServicesTools/Functions/Security/Rest/Revoke-RsRestItemAccessPolicy.ps1

Fix error 500 in Revoke-RsRestItemAccessPolicy when using credentials and not relying on  -UseDefaultCredentials
- Powershell 7 and above
- SQL Server 2019 and above

Fix error in Revoke-RsRestItemAccessPolicy

---

ReportingServicesTools/Functions/Security/Rest/Get-RsRestItemAccessPolicy.ps1
ReportingServicesTools/Functions/Security/Rest/Grant-RsRestItemAccessPolicy.ps1
ReportingServicesTools/Functions/Security/Rest/Revoke-RsRestItemAccessPolicy.ps1

- Powershell 7 and above
- SQL Server 2019 and above

Fix error 500 with *-RsRestItemAccessPolicy functions

---

ReportingServicesTools/Functions/Admin/Rest/Get-RsRestPublicServerSetting.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestCacheRefreshPlanHistory.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItemDataModelParameters.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Get-RsRestItemDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/New-RsRestFolder.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItemId.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestFolderContent.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestFolder.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataModelParameters.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Set-RsRestItemDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Start-RsRestCacheRefreshPlan.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Test-RsRestItemDataSource.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1
ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestFolderContent.ps1
ReportingServicesTools/Functions/Security/Rest/Get-RsRestItemAccessPolicy.ps1
ReportingServicesTools/Functions/Security/Rest/Grant-RsRestItemAccessPolicy.ps1
ReportingServicesTools/Functions/Security/Rest/Revoke-RsRestItemAccessPolicy.ps1

Fixes #377.
- If passing a WebSession and the Credentials are not supplied, the code checks if the credentials were originally set in New-RsRestSession call and retrieves those for use in the function
- I have tested rest code using web sessions with and without passing the credentials in the individual calls
- I have also did some basic testing when using -DefaultCredentials parameter and it all seems to work as expected.
- Powershell 5 and above

Fix #377 by loading creds from session unless provided

---

ReportingServicesTools/Functions/Admin/Restore-RsEncryptionKey.ps1

Fixes https://github.com/microsoft/ReportingServicesTools/issues/384 .
Changes Resolve-Path to examine the path as a Parent and Child instead of as a single unit to avoid damaging the proper UNC path.
Restore-RSEncryptionKey -ReportServerInstance "Instance" -Password "Password" -KeyPath "\domain\share\folder\keyfile.snk"
(Testing outside the module requires functions in ShouldProcess.ps1 and ConnectionObjectRequests.ps1)
PSVersion 5.1.17763.2931
Windows Server 2019 Datacenter
SQL Server 2016

Fixed issue with Resolve-Path breaking UNC keypaths.

---

ReportingServicesTools/Functions/CatalogItems/Rest/Out-RsRestCatalogItemId.ps1

Exclude Linked Reports from being downloaded by the function Out-RsRestCatalogItemId because it cannot download them anyway. It was causing bugs when wanting to download content from Report Server (type was not invalid).
- Exclude Linked Reports from the list of downloadable items of Report Server
- Create a Linked Report in your Report Server and use this function to download the content of Report Server. It will ignore the Linked Report and download other reports as usual.
- Windows 10

Exclude Linked Reports

---

ReportingServicesTools/Functions/CatalogItems/Publish-RsProject.ps1

Changed in the documentation path of .EXAMPLE where the input parameter name should be -RsProjectFile instead of -RsProjectFile.
Fixes # .
- Fix in the documentation to rename the parameter to Get-RsDeploymentConfig from -ProjectFile to -RsProjectFile.
- There is only change to documentation example which is commented and no changes done in the code. To test this we should be running only Publish-RsProject.ps1 to make sure it does not impact on the existing functionality. 

Update Publish-RsProject.ps1 - Change in the Documentation example section to have the correct Parameter name.

---

ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1
ReportingServicesTools/Functions/Admin/Set-RsDatabaseCredentials.ps1

`Set-RsDatabase` script started to result in failure with the following error:
> Executing database creation script... Failed!
> Invoke-Sqlcmd : A connection was successfully established with the server, but then an error occurred during the login
> process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
After investigation, I discovered that this behavior is a result of the recent update of SQL [Strict Connection Encryption](https://learn.microsoft.com/en-us/sql/relational-databases/security/networking/tds-8-and-tls-1-3?view=sql-server-ver16#strict-connection-encryption), which introduced some changes to the defaults of SQL connection encryption.
Since v22, `Invoke-Sqlcmd` cmdlet from PowerShell SqlServer module has three new …

Updated Set-RsDatabase and Set-RsDatabaseCredentials scripts to support new parameters of Invoke-Sqlcmd.

---

ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1
ReportingServicesTools/Functions/Admin/Set-RsDatabaseCredentials.ps1

This is the reopened Pull Request #401, which was [reverted](https://github.com/microsoft/ReportingServicesTools/pull/403).
I investigated the build failures and it doesn't look like they are caused by the changes in this PR.
The logs show that both `Set-RsDatabase` and `Set-RsDatabaseCredentials` scripts were executed successfully.
The build fails after a number of attempts to make a POST request to the server resulting in the response with 503 status code each time.
The error message says: “_Failed to update the AllowedResourceExtensionsForUpload_”.
As I understand, the server fails to get initialized correctly before appveyor script starts to send the requests to it.
Here are some obvious examples of other merged PRs having the build failing with the same error: 
- #385 …

[Reopened] Updated Set-RsDatabase and Set-RsDatabaseCredentials scripts to support new parameters of Invoke-Sqlcmd.

---

ReportingServicesTools/Functions/Common/Get-ItemType.ps1

Add .xlsm (Microsoft Excel macro-enabled spreadsheet) to the type lookup. XLSM files are supported by Power BI but until now they could not be uploaded, refer to issue #349.
Fixes #349.
- Adds a single line to Get-ItemType.ps1 for the .xlsm file type
- Minor reformat of layout (spacing) for neatness
- Create an .xlsm file in Excel, save it as C:\Temp\Just_a_test.xlsm
- Upload the file using `Write-RsRestCatalogItem -ReportPortalURI $youruri -Path 'C:\Temp\Just_a_test.xlsm' -RsFolder $DestFolder`
(Previously this would fail with an error message - (400) Bad Request. After this change to Get-ItemType.ps1 it seems to run without any issues.)
- Windows Server 2016

Add .xlsm as known file type

---

ReportingServicesTools/Libraries/library.ps1

fix https://github.com/microsoft/ReportingServicesTools/issues/435#issuecomment-2697265750.
Importing ReportingServicesTools Module...
C:\Users\Akash\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Libraries\library.ps
1 : Error: Cannot add type. The type name 'Microsoft.ReportingServicesTools.ConnectionHost' already exists.
At C:\Users\Akash\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\ReportingServices
Tools.psm1:1 char:1
Remove-Module can't fully unload a module, so when re-importing the module, it threw the error "the type already exists", using warning instead of error to unblock install.ps1

Update library.ps1: Use Write-Warning instead of Write-Error for catch block
